[globals]

[general]
autofallthrough=yes
priorityjumping=no

[from-3cx]
; Appel entrant depuis 3CX vers l'IA
exten => s,1,NoOp(Appel entrant depuis 3CX)
 same => n,Answer()
 same => n,Answer()
 same => n,AudioSocket(127.0.0.1,5000)
 same => n,Hangup()

[default]
include => from-3cx
