[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[3cx-trunk]
type=endpoint
context=from-3cx
disallow=all
allow=ulaw,alaw
transport=transport-udp

[3cx-registration]
type=registration
transport=transport-udp
outbound_auth=3cx-auth
server_uri=sip:1142.3cx.cloud:5060
client_uri=sip:48013@1142.3cx.cloud:5060
contact_user=48013
retry_interval=60
forbidden_retry_interval=300
expiration=3600

[3cx-auth]
type=auth
auth_type=userpass
username=48013
password=Mirindra1724!

[3cx-aor]
type=aor
contact=sip:1142.3cx.cloud:5060
